linters:
  enable-all: true
  disable:
    - depguard
    - lll
    - nlreturn
    - wsl
    - mnd
    - tenv
    - gochecknoinits
    - err113
    - exhaustruct
    - forbidigo
    - gochecknoglobals
    - varnamelen
